# Generated by Django 6.0.2 on 2026-06-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_patient_age_remove_patient_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
