# Generated by Django 6.0.2 on 2026-06-24 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('patients', 'Patients'), ('appointments', 'Appointments'), ('doctors', 'Doctors'), ('staff', 'Staff'), ('reports', 'Reports')], max_length=50)),
                ('access', models.CharField(choices=[('none', 'No Access'), ('read', 'Read Only'), ('write', 'Write Only'), ('both', 'Read & Write')], default='none', max_length=10)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='access_control.role')),
            ],
            options={
                'unique_together': {('role', 'module')},
            },
        ),
    ]
