# Generated by Django 6.0.2 on 2026-06-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_modulepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepermission',
            name='access',
            field=models.CharField(choices=[('no_access', 'No Access'), ('read', 'Read'), ('full_access', 'Full Access')], default='no_access', max_length=15),
        ),
    ]
