# Generated by Django 6.0.2 on 2026-06-25 18:07

from django.db import migrations


def forwards(apps, schema_editor):
    ModulePermission = apps.get_model("access_control", "ModulePermission")
    ModulePermission.objects.filter(
        access__in=["write", "both", "read_write"]
    ).update(access="full_access")
    ModulePermission.objects.filter(access="none").update(access="no_access")


def backwards(apps, schema_editor):
    ModulePermission = apps.get_model("access_control", "ModulePermission")
    ModulePermission.objects.filter(access="full_access").update(access="both")
    ModulePermission.objects.filter(access="no_access").update(access="none")


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0003_normalise_access_choices'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
