# Generated by Django 6.0.2 on 2026-06-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_add_email_has_account_user_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
