# Generated by Django 6.0.2 on 2026-06-22 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_display_name_organization_logo'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='shift_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shift_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='specializations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='DoctorAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('checkin_time', models.TimeField(blank=True, null=True)),
                ('checkout_time', models.TimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='organizations.organization')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('doctor', 'date')},
            },
        ),
    ]
