# Generated by Django 6.0.2 on 2026-06-24 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_modulepermission'),
        ('users', '0002_user_experience_years_user_join_date_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='access_control.role'),
        ),
    ]
