# Generated by Django 6.0.2 on 2026-06-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_populate_qualification_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='force_password_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_account',
            field=models.BooleanField(default=False),
        ),
    ]
